// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageEntity.proto

package com.github.zhenwei.proto;

public final class MineMessage {
  private MineMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *标识用那个枚举类型, 为MyMessage类中的第一个属性
     * </pre>
     *
     * <code>.MyMessage.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     *标识用那个枚举类型, 为MyMessage类中的第一个属性
     * </pre>
     *
     * <code>.MyMessage.Type type = 1;</code>
     * @return The type.
     */
    com.github.zhenwei.proto.MineMessage.MyMessage.Type getType();

    /**
     * <code>.Person person = 2;</code>
     * @return Whether the person field is set.
     */
    boolean hasPerson();
    /**
     * <code>.Person person = 2;</code>
     * @return The person.
     */
    com.github.zhenwei.proto.MineMessage.Person getPerson();
    /**
     * <code>.Person person = 2;</code>
     */
    com.github.zhenwei.proto.MineMessage.PersonOrBuilder getPersonOrBuilder();

    /**
     * <code>.Worker worker = 3;</code>
     * @return Whether the worker field is set.
     */
    boolean hasWorker();
    /**
     * <code>.Worker worker = 3;</code>
     * @return The worker.
     */
    com.github.zhenwei.proto.MineMessage.Worker getWorker();
    /**
     * <code>.Worker worker = 3;</code>
     */
    com.github.zhenwei.proto.MineMessage.WorkerOrBuilder getWorkerOrBuilder();

    /**
     * <code>string message = 4;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 4;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    public com.github.zhenwei.proto.MineMessage.MyMessage.TypeBodyCase getTypeBodyCase();
  }
  /**
   * <pre>
   * 执行命令: protoc MessageEntity.proto --java_out=/Users/...
   * </pre>
   *
   * Protobuf type {@code MyMessage}
   */
  public static final class MyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MyMessage)
      MyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessage() {
      type_ = 0;
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MyMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              com.github.zhenwei.proto.MineMessage.Person.Builder subBuilder = null;
              if (typeBodyCase_ == 2) {
                subBuilder = ((com.github.zhenwei.proto.MineMessage.Person) typeBody_).toBuilder();
              }
              typeBody_ =
                  input.readMessage(com.github.zhenwei.proto.MineMessage.Person.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.github.zhenwei.proto.MineMessage.Person) typeBody_);
                typeBody_ = subBuilder.buildPartial();
              }
              typeBodyCase_ = 2;
              break;
            }
            case 26: {
              com.github.zhenwei.proto.MineMessage.Worker.Builder subBuilder = null;
              if (typeBodyCase_ == 3) {
                subBuilder = ((com.github.zhenwei.proto.MineMessage.Worker) typeBody_).toBuilder();
              }
              typeBody_ =
                  input.readMessage(com.github.zhenwei.proto.MineMessage.Worker.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.github.zhenwei.proto.MineMessage.Worker) typeBody_);
                typeBody_ = subBuilder.buildPartial();
              }
              typeBodyCase_ = 3;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.zhenwei.proto.MineMessage.internal_static_MyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.zhenwei.proto.MineMessage.internal_static_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.zhenwei.proto.MineMessage.MyMessage.class, com.github.zhenwei.proto.MineMessage.MyMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code MyMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *必须从 0 开始
       * </pre>
       *
       * <code>PERSON_TYPE = 0;</code>
       */
      PERSON_TYPE(0),
      /**
       * <code>WORKER_TYPE = 1;</code>
       */
      WORKER_TYPE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *必须从 0 开始
       * </pre>
       *
       * <code>PERSON_TYPE = 0;</code>
       */
      public static final int PERSON_TYPE_VALUE = 0;
      /**
       * <code>WORKER_TYPE = 1;</code>
       */
      public static final int WORKER_TYPE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return PERSON_TYPE;
          case 1: return WORKER_TYPE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.github.zhenwei.proto.MineMessage.MyMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MyMessage.Type)
    }

    private int typeBodyCase_ = 0;
    private java.lang.Object typeBody_;
    public enum TypeBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      PERSON(2),
      WORKER(3),
      TYPEBODY_NOT_SET(0);
      private final int value;
      private TypeBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TypeBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static TypeBodyCase forNumber(int value) {
        switch (value) {
          case 2: return PERSON;
          case 3: return WORKER;
          case 0: return TYPEBODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TypeBodyCase
    getTypeBodyCase() {
      return TypeBodyCase.forNumber(
          typeBodyCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *标识用那个枚举类型, 为MyMessage类中的第一个属性
     * </pre>
     *
     * <code>.MyMessage.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *标识用那个枚举类型, 为MyMessage类中的第一个属性
     * </pre>
     *
     * <code>.MyMessage.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public com.github.zhenwei.proto.MineMessage.MyMessage.Type getType() {
      @SuppressWarnings("deprecation")
      com.github.zhenwei.proto.MineMessage.MyMessage.Type result = com.github.zhenwei.proto.MineMessage.MyMessage.Type.valueOf(type_);
      return result == null ? com.github.zhenwei.proto.MineMessage.MyMessage.Type.UNRECOGNIZED : result;
    }

    public static final int PERSON_FIELD_NUMBER = 2;
    /**
     * <code>.Person person = 2;</code>
     * @return Whether the person field is set.
     */
    @java.lang.Override
    public boolean hasPerson() {
      return typeBodyCase_ == 2;
    }
    /**
     * <code>.Person person = 2;</code>
     * @return The person.
     */
    @java.lang.Override
    public com.github.zhenwei.proto.MineMessage.Person getPerson() {
      if (typeBodyCase_ == 2) {
         return (com.github.zhenwei.proto.MineMessage.Person) typeBody_;
      }
      return com.github.zhenwei.proto.MineMessage.Person.getDefaultInstance();
    }
    /**
     * <code>.Person person = 2;</code>
     */
    @java.lang.Override
    public com.github.zhenwei.proto.MineMessage.PersonOrBuilder getPersonOrBuilder() {
      if (typeBodyCase_ == 2) {
         return (com.github.zhenwei.proto.MineMessage.Person) typeBody_;
      }
      return com.github.zhenwei.proto.MineMessage.Person.getDefaultInstance();
    }

    public static final int WORKER_FIELD_NUMBER = 3;
    /**
     * <code>.Worker worker = 3;</code>
     * @return Whether the worker field is set.
     */
    @java.lang.Override
    public boolean hasWorker() {
      return typeBodyCase_ == 3;
    }
    /**
     * <code>.Worker worker = 3;</code>
     * @return The worker.
     */
    @java.lang.Override
    public com.github.zhenwei.proto.MineMessage.Worker getWorker() {
      if (typeBodyCase_ == 3) {
         return (com.github.zhenwei.proto.MineMessage.Worker) typeBody_;
      }
      return com.github.zhenwei.proto.MineMessage.Worker.getDefaultInstance();
    }
    /**
     * <code>.Worker worker = 3;</code>
     */
    @java.lang.Override
    public com.github.zhenwei.proto.MineMessage.WorkerOrBuilder getWorkerOrBuilder() {
      if (typeBodyCase_ == 3) {
         return (com.github.zhenwei.proto.MineMessage.Worker) typeBody_;
      }
      return com.github.zhenwei.proto.MineMessage.Worker.getDefaultInstance();
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 4;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 4;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.github.zhenwei.proto.MineMessage.MyMessage.Type.PERSON_TYPE.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (typeBodyCase_ == 2) {
        output.writeMessage(2, (com.github.zhenwei.proto.MineMessage.Person) typeBody_);
      }
      if (typeBodyCase_ == 3) {
        output.writeMessage(3, (com.github.zhenwei.proto.MineMessage.Worker) typeBody_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.github.zhenwei.proto.MineMessage.MyMessage.Type.PERSON_TYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (typeBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.github.zhenwei.proto.MineMessage.Person) typeBody_);
      }
      if (typeBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.github.zhenwei.proto.MineMessage.Worker) typeBody_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.zhenwei.proto.MineMessage.MyMessage)) {
        return super.equals(obj);
      }
      com.github.zhenwei.proto.MineMessage.MyMessage other = (com.github.zhenwei.proto.MineMessage.MyMessage) obj;

      if (type_ != other.type_) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getTypeBodyCase().equals(other.getTypeBodyCase())) return false;
      switch (typeBodyCase_) {
        case 2:
          if (!getPerson()
              .equals(other.getPerson())) return false;
          break;
        case 3:
          if (!getWorker()
              .equals(other.getWorker())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      switch (typeBodyCase_) {
        case 2:
          hash = (37 * hash) + PERSON_FIELD_NUMBER;
          hash = (53 * hash) + getPerson().hashCode();
          break;
        case 3:
          hash = (37 * hash) + WORKER_FIELD_NUMBER;
          hash = (53 * hash) + getWorker().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.zhenwei.proto.MineMessage.MyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.zhenwei.proto.MineMessage.MyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.zhenwei.proto.MineMessage.MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.zhenwei.proto.MineMessage.MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.zhenwei.proto.MineMessage.MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.zhenwei.proto.MineMessage.MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.zhenwei.proto.MineMessage.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.zhenwei.proto.MineMessage.MyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 执行命令: protoc MessageEntity.proto --java_out=/Users/...
     * </pre>
     *
     * Protobuf type {@code MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MyMessage)
        com.github.zhenwei.proto.MineMessage.MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.zhenwei.proto.MineMessage.internal_static_MyMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.zhenwei.proto.MineMessage.internal_static_MyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.zhenwei.proto.MineMessage.MyMessage.class, com.github.zhenwei.proto.MineMessage.MyMessage.Builder.class);
      }

      // Construct using com.github.zhenwei.proto.MineMessage.MyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        message_ = "";

        typeBodyCase_ = 0;
        typeBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.zhenwei.proto.MineMessage.internal_static_MyMessage_descriptor;
      }

      @java.lang.Override
      public com.github.zhenwei.proto.MineMessage.MyMessage getDefaultInstanceForType() {
        return com.github.zhenwei.proto.MineMessage.MyMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.zhenwei.proto.MineMessage.MyMessage build() {
        com.github.zhenwei.proto.MineMessage.MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.zhenwei.proto.MineMessage.MyMessage buildPartial() {
        com.github.zhenwei.proto.MineMessage.MyMessage result = new com.github.zhenwei.proto.MineMessage.MyMessage(this);
        result.type_ = type_;
        if (typeBodyCase_ == 2) {
          if (personBuilder_ == null) {
            result.typeBody_ = typeBody_;
          } else {
            result.typeBody_ = personBuilder_.build();
          }
        }
        if (typeBodyCase_ == 3) {
          if (workerBuilder_ == null) {
            result.typeBody_ = typeBody_;
          } else {
            result.typeBody_ = workerBuilder_.build();
          }
        }
        result.message_ = message_;
        result.typeBodyCase_ = typeBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.zhenwei.proto.MineMessage.MyMessage) {
          return mergeFrom((com.github.zhenwei.proto.MineMessage.MyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.zhenwei.proto.MineMessage.MyMessage other) {
        if (other == com.github.zhenwei.proto.MineMessage.MyMessage.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        switch (other.getTypeBodyCase()) {
          case PERSON: {
            mergePerson(other.getPerson());
            break;
          }
          case WORKER: {
            mergeWorker(other.getWorker());
            break;
          }
          case TYPEBODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.zhenwei.proto.MineMessage.MyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.zhenwei.proto.MineMessage.MyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int typeBodyCase_ = 0;
      private java.lang.Object typeBody_;
      public TypeBodyCase
          getTypeBodyCase() {
        return TypeBodyCase.forNumber(
            typeBodyCase_);
      }

      public Builder clearTypeBody() {
        typeBodyCase_ = 0;
        typeBody_ = null;
        onChanged();
        return this;
      }


      private int type_ = 0;
      /**
       * <pre>
       *标识用那个枚举类型, 为MyMessage类中的第一个属性
       * </pre>
       *
       * <code>.MyMessage.Type type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *标识用那个枚举类型, 为MyMessage类中的第一个属性
       * </pre>
       *
       * <code>.MyMessage.Type type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *标识用那个枚举类型, 为MyMessage类中的第一个属性
       * </pre>
       *
       * <code>.MyMessage.Type type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.github.zhenwei.proto.MineMessage.MyMessage.Type getType() {
        @SuppressWarnings("deprecation")
        com.github.zhenwei.proto.MineMessage.MyMessage.Type result = com.github.zhenwei.proto.MineMessage.MyMessage.Type.valueOf(type_);
        return result == null ? com.github.zhenwei.proto.MineMessage.MyMessage.Type.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *标识用那个枚举类型, 为MyMessage类中的第一个属性
       * </pre>
       *
       * <code>.MyMessage.Type type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.github.zhenwei.proto.MineMessage.MyMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *标识用那个枚举类型, 为MyMessage类中的第一个属性
       * </pre>
       *
       * <code>.MyMessage.Type type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.zhenwei.proto.MineMessage.Person, com.github.zhenwei.proto.MineMessage.Person.Builder, com.github.zhenwei.proto.MineMessage.PersonOrBuilder> personBuilder_;
      /**
       * <code>.Person person = 2;</code>
       * @return Whether the person field is set.
       */
      @java.lang.Override
      public boolean hasPerson() {
        return typeBodyCase_ == 2;
      }
      /**
       * <code>.Person person = 2;</code>
       * @return The person.
       */
      @java.lang.Override
      public com.github.zhenwei.proto.MineMessage.Person getPerson() {
        if (personBuilder_ == null) {
          if (typeBodyCase_ == 2) {
            return (com.github.zhenwei.proto.MineMessage.Person) typeBody_;
          }
          return com.github.zhenwei.proto.MineMessage.Person.getDefaultInstance();
        } else {
          if (typeBodyCase_ == 2) {
            return personBuilder_.getMessage();
          }
          return com.github.zhenwei.proto.MineMessage.Person.getDefaultInstance();
        }
      }
      /**
       * <code>.Person person = 2;</code>
       */
      public Builder setPerson(com.github.zhenwei.proto.MineMessage.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          typeBody_ = value;
          onChanged();
        } else {
          personBuilder_.setMessage(value);
        }
        typeBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Person person = 2;</code>
       */
      public Builder setPerson(
          com.github.zhenwei.proto.MineMessage.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          typeBody_ = builderForValue.build();
          onChanged();
        } else {
          personBuilder_.setMessage(builderForValue.build());
        }
        typeBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Person person = 2;</code>
       */
      public Builder mergePerson(com.github.zhenwei.proto.MineMessage.Person value) {
        if (personBuilder_ == null) {
          if (typeBodyCase_ == 2 &&
              typeBody_ != com.github.zhenwei.proto.MineMessage.Person.getDefaultInstance()) {
            typeBody_ = com.github.zhenwei.proto.MineMessage.Person.newBuilder((com.github.zhenwei.proto.MineMessage.Person) typeBody_)
                .mergeFrom(value).buildPartial();
          } else {
            typeBody_ = value;
          }
          onChanged();
        } else {
          if (typeBodyCase_ == 2) {
            personBuilder_.mergeFrom(value);
          }
          personBuilder_.setMessage(value);
        }
        typeBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Person person = 2;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          if (typeBodyCase_ == 2) {
            typeBodyCase_ = 0;
            typeBody_ = null;
            onChanged();
          }
        } else {
          if (typeBodyCase_ == 2) {
            typeBodyCase_ = 0;
            typeBody_ = null;
          }
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Person person = 2;</code>
       */
      public com.github.zhenwei.proto.MineMessage.Person.Builder getPersonBuilder() {
        return getPersonFieldBuilder().getBuilder();
      }
      /**
       * <code>.Person person = 2;</code>
       */
      @java.lang.Override
      public com.github.zhenwei.proto.MineMessage.PersonOrBuilder getPersonOrBuilder() {
        if ((typeBodyCase_ == 2) && (personBuilder_ != null)) {
          return personBuilder_.getMessageOrBuilder();
        } else {
          if (typeBodyCase_ == 2) {
            return (com.github.zhenwei.proto.MineMessage.Person) typeBody_;
          }
          return com.github.zhenwei.proto.MineMessage.Person.getDefaultInstance();
        }
      }
      /**
       * <code>.Person person = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.zhenwei.proto.MineMessage.Person, com.github.zhenwei.proto.MineMessage.Person.Builder, com.github.zhenwei.proto.MineMessage.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          if (!(typeBodyCase_ == 2)) {
            typeBody_ = com.github.zhenwei.proto.MineMessage.Person.getDefaultInstance();
          }
          personBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.github.zhenwei.proto.MineMessage.Person, com.github.zhenwei.proto.MineMessage.Person.Builder, com.github.zhenwei.proto.MineMessage.PersonOrBuilder>(
                  (com.github.zhenwei.proto.MineMessage.Person) typeBody_,
                  getParentForChildren(),
                  isClean());
          typeBody_ = null;
        }
        typeBodyCase_ = 2;
        onChanged();;
        return personBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.zhenwei.proto.MineMessage.Worker, com.github.zhenwei.proto.MineMessage.Worker.Builder, com.github.zhenwei.proto.MineMessage.WorkerOrBuilder> workerBuilder_;
      /**
       * <code>.Worker worker = 3;</code>
       * @return Whether the worker field is set.
       */
      @java.lang.Override
      public boolean hasWorker() {
        return typeBodyCase_ == 3;
      }
      /**
       * <code>.Worker worker = 3;</code>
       * @return The worker.
       */
      @java.lang.Override
      public com.github.zhenwei.proto.MineMessage.Worker getWorker() {
        if (workerBuilder_ == null) {
          if (typeBodyCase_ == 3) {
            return (com.github.zhenwei.proto.MineMessage.Worker) typeBody_;
          }
          return com.github.zhenwei.proto.MineMessage.Worker.getDefaultInstance();
        } else {
          if (typeBodyCase_ == 3) {
            return workerBuilder_.getMessage();
          }
          return com.github.zhenwei.proto.MineMessage.Worker.getDefaultInstance();
        }
      }
      /**
       * <code>.Worker worker = 3;</code>
       */
      public Builder setWorker(com.github.zhenwei.proto.MineMessage.Worker value) {
        if (workerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          typeBody_ = value;
          onChanged();
        } else {
          workerBuilder_.setMessage(value);
        }
        typeBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Worker worker = 3;</code>
       */
      public Builder setWorker(
          com.github.zhenwei.proto.MineMessage.Worker.Builder builderForValue) {
        if (workerBuilder_ == null) {
          typeBody_ = builderForValue.build();
          onChanged();
        } else {
          workerBuilder_.setMessage(builderForValue.build());
        }
        typeBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Worker worker = 3;</code>
       */
      public Builder mergeWorker(com.github.zhenwei.proto.MineMessage.Worker value) {
        if (workerBuilder_ == null) {
          if (typeBodyCase_ == 3 &&
              typeBody_ != com.github.zhenwei.proto.MineMessage.Worker.getDefaultInstance()) {
            typeBody_ = com.github.zhenwei.proto.MineMessage.Worker.newBuilder((com.github.zhenwei.proto.MineMessage.Worker) typeBody_)
                .mergeFrom(value).buildPartial();
          } else {
            typeBody_ = value;
          }
          onChanged();
        } else {
          if (typeBodyCase_ == 3) {
            workerBuilder_.mergeFrom(value);
          }
          workerBuilder_.setMessage(value);
        }
        typeBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Worker worker = 3;</code>
       */
      public Builder clearWorker() {
        if (workerBuilder_ == null) {
          if (typeBodyCase_ == 3) {
            typeBodyCase_ = 0;
            typeBody_ = null;
            onChanged();
          }
        } else {
          if (typeBodyCase_ == 3) {
            typeBodyCase_ = 0;
            typeBody_ = null;
          }
          workerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Worker worker = 3;</code>
       */
      public com.github.zhenwei.proto.MineMessage.Worker.Builder getWorkerBuilder() {
        return getWorkerFieldBuilder().getBuilder();
      }
      /**
       * <code>.Worker worker = 3;</code>
       */
      @java.lang.Override
      public com.github.zhenwei.proto.MineMessage.WorkerOrBuilder getWorkerOrBuilder() {
        if ((typeBodyCase_ == 3) && (workerBuilder_ != null)) {
          return workerBuilder_.getMessageOrBuilder();
        } else {
          if (typeBodyCase_ == 3) {
            return (com.github.zhenwei.proto.MineMessage.Worker) typeBody_;
          }
          return com.github.zhenwei.proto.MineMessage.Worker.getDefaultInstance();
        }
      }
      /**
       * <code>.Worker worker = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.zhenwei.proto.MineMessage.Worker, com.github.zhenwei.proto.MineMessage.Worker.Builder, com.github.zhenwei.proto.MineMessage.WorkerOrBuilder> 
          getWorkerFieldBuilder() {
        if (workerBuilder_ == null) {
          if (!(typeBodyCase_ == 3)) {
            typeBody_ = com.github.zhenwei.proto.MineMessage.Worker.getDefaultInstance();
          }
          workerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.github.zhenwei.proto.MineMessage.Worker, com.github.zhenwei.proto.MineMessage.Worker.Builder, com.github.zhenwei.proto.MineMessage.WorkerOrBuilder>(
                  (com.github.zhenwei.proto.MineMessage.Worker) typeBody_,
                  getParentForChildren(),
                  isClean());
          typeBody_ = null;
        }
        typeBodyCase_ = 3;
        onChanged();;
        return workerBuilder_;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 4;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 4;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 4;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 4;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MyMessage)
    }

    // @@protoc_insertion_point(class_scope:MyMessage)
    private static final com.github.zhenwei.proto.MineMessage.MyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.zhenwei.proto.MineMessage.MyMessage();
    }

    public static com.github.zhenwei.proto.MineMessage.MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyMessage>
        PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
      @java.lang.Override
      public MyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.zhenwei.proto.MineMessage.MyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>string addr = 4;</code>
     * @return The addr.
     */
    java.lang.String getAddr();
    /**
     * <code>string addr = 4;</code>
     * @return The bytes for addr.
     */
    com.google.protobuf.ByteString
        getAddrBytes();
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      addr_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              addr_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.zhenwei.proto.MineMessage.internal_static_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.zhenwei.proto.MineMessage.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.zhenwei.proto.MineMessage.Person.class, com.github.zhenwei.proto.MineMessage.Person.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int ADDR_FIELD_NUMBER = 4;
    private volatile java.lang.Object addr_;
    /**
     * <code>string addr = 4;</code>
     * @return The addr.
     */
    @java.lang.Override
    public java.lang.String getAddr() {
      java.lang.Object ref = addr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addr_ = s;
        return s;
      }
    }
    /**
     * <code>string addr = 4;</code>
     * @return The bytes for addr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddrBytes() {
      java.lang.Object ref = addr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(addr_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, addr_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(addr_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, addr_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.zhenwei.proto.MineMessage.Person)) {
        return super.equals(obj);
      }
      com.github.zhenwei.proto.MineMessage.Person other = (com.github.zhenwei.proto.MineMessage.Person) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getAddr()
          .equals(other.getAddr())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getAddr().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.zhenwei.proto.MineMessage.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.zhenwei.proto.MineMessage.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.zhenwei.proto.MineMessage.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.zhenwei.proto.MineMessage.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.zhenwei.proto.MineMessage.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.zhenwei.proto.MineMessage.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.zhenwei.proto.MineMessage.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.zhenwei.proto.MineMessage.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        com.github.zhenwei.proto.MineMessage.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.zhenwei.proto.MineMessage.internal_static_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.zhenwei.proto.MineMessage.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.zhenwei.proto.MineMessage.Person.class, com.github.zhenwei.proto.MineMessage.Person.Builder.class);
      }

      // Construct using com.github.zhenwei.proto.MineMessage.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        addr_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.zhenwei.proto.MineMessage.internal_static_Person_descriptor;
      }

      @java.lang.Override
      public com.github.zhenwei.proto.MineMessage.Person getDefaultInstanceForType() {
        return com.github.zhenwei.proto.MineMessage.Person.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.zhenwei.proto.MineMessage.Person build() {
        com.github.zhenwei.proto.MineMessage.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.zhenwei.proto.MineMessage.Person buildPartial() {
        com.github.zhenwei.proto.MineMessage.Person result = new com.github.zhenwei.proto.MineMessage.Person(this);
        result.name_ = name_;
        result.age_ = age_;
        result.addr_ = addr_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.zhenwei.proto.MineMessage.Person) {
          return mergeFrom((com.github.zhenwei.proto.MineMessage.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.zhenwei.proto.MineMessage.Person other) {
        if (other == com.github.zhenwei.proto.MineMessage.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getAddr().isEmpty()) {
          addr_ = other.addr_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.zhenwei.proto.MineMessage.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.zhenwei.proto.MineMessage.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 3;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 3;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object addr_ = "";
      /**
       * <code>string addr = 4;</code>
       * @return The addr.
       */
      public java.lang.String getAddr() {
        java.lang.Object ref = addr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string addr = 4;</code>
       * @return The bytes for addr.
       */
      public com.google.protobuf.ByteString
          getAddrBytes() {
        java.lang.Object ref = addr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string addr = 4;</code>
       * @param value The addr to set.
       * @return This builder for chaining.
       */
      public Builder setAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        addr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string addr = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddr() {
        
        addr_ = getDefaultInstance().getAddr();
        onChanged();
        return this;
      }
      /**
       * <code>string addr = 4;</code>
       * @param value The bytes for addr to set.
       * @return This builder for chaining.
       */
      public Builder setAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        addr_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final com.github.zhenwei.proto.MineMessage.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.zhenwei.proto.MineMessage.Person();
    }

    public static com.github.zhenwei.proto.MineMessage.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.zhenwei.proto.MineMessage.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WorkerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Worker)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string handle = 1;</code>
     * @return The handle.
     */
    java.lang.String getHandle();
    /**
     * <code>string handle = 1;</code>
     * @return The bytes for handle.
     */
    com.google.protobuf.ByteString
        getHandleBytes();

    /**
     * <code>string workerTime = 2;</code>
     * @return The workerTime.
     */
    java.lang.String getWorkerTime();
    /**
     * <code>string workerTime = 2;</code>
     * @return The bytes for workerTime.
     */
    com.google.protobuf.ByteString
        getWorkerTimeBytes();
  }
  /**
   * Protobuf type {@code Worker}
   */
  public static final class Worker extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Worker)
      WorkerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Worker.newBuilder() to construct.
    private Worker(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Worker() {
      handle_ = "";
      workerTime_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Worker();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Worker(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              handle_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              workerTime_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.zhenwei.proto.MineMessage.internal_static_Worker_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.zhenwei.proto.MineMessage.internal_static_Worker_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.zhenwei.proto.MineMessage.Worker.class, com.github.zhenwei.proto.MineMessage.Worker.Builder.class);
    }

    public static final int HANDLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object handle_;
    /**
     * <code>string handle = 1;</code>
     * @return The handle.
     */
    @java.lang.Override
    public java.lang.String getHandle() {
      java.lang.Object ref = handle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        handle_ = s;
        return s;
      }
    }
    /**
     * <code>string handle = 1;</code>
     * @return The bytes for handle.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHandleBytes() {
      java.lang.Object ref = handle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        handle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WORKERTIME_FIELD_NUMBER = 2;
    private volatile java.lang.Object workerTime_;
    /**
     * <code>string workerTime = 2;</code>
     * @return The workerTime.
     */
    @java.lang.Override
    public java.lang.String getWorkerTime() {
      java.lang.Object ref = workerTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workerTime_ = s;
        return s;
      }
    }
    /**
     * <code>string workerTime = 2;</code>
     * @return The bytes for workerTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWorkerTimeBytes() {
      java.lang.Object ref = workerTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workerTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(handle_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, handle_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(workerTime_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, workerTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(handle_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, handle_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(workerTime_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, workerTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.zhenwei.proto.MineMessage.Worker)) {
        return super.equals(obj);
      }
      com.github.zhenwei.proto.MineMessage.Worker other = (com.github.zhenwei.proto.MineMessage.Worker) obj;

      if (!getHandle()
          .equals(other.getHandle())) return false;
      if (!getWorkerTime()
          .equals(other.getWorkerTime())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HANDLE_FIELD_NUMBER;
      hash = (53 * hash) + getHandle().hashCode();
      hash = (37 * hash) + WORKERTIME_FIELD_NUMBER;
      hash = (53 * hash) + getWorkerTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.zhenwei.proto.MineMessage.Worker parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.zhenwei.proto.MineMessage.Worker parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.Worker parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.zhenwei.proto.MineMessage.Worker parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.Worker parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.zhenwei.proto.MineMessage.Worker parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.Worker parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.zhenwei.proto.MineMessage.Worker parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.Worker parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.zhenwei.proto.MineMessage.Worker parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.zhenwei.proto.MineMessage.Worker parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.zhenwei.proto.MineMessage.Worker parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.zhenwei.proto.MineMessage.Worker prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Worker}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Worker)
        com.github.zhenwei.proto.MineMessage.WorkerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.zhenwei.proto.MineMessage.internal_static_Worker_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.zhenwei.proto.MineMessage.internal_static_Worker_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.zhenwei.proto.MineMessage.Worker.class, com.github.zhenwei.proto.MineMessage.Worker.Builder.class);
      }

      // Construct using com.github.zhenwei.proto.MineMessage.Worker.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        handle_ = "";

        workerTime_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.zhenwei.proto.MineMessage.internal_static_Worker_descriptor;
      }

      @java.lang.Override
      public com.github.zhenwei.proto.MineMessage.Worker getDefaultInstanceForType() {
        return com.github.zhenwei.proto.MineMessage.Worker.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.zhenwei.proto.MineMessage.Worker build() {
        com.github.zhenwei.proto.MineMessage.Worker result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.zhenwei.proto.MineMessage.Worker buildPartial() {
        com.github.zhenwei.proto.MineMessage.Worker result = new com.github.zhenwei.proto.MineMessage.Worker(this);
        result.handle_ = handle_;
        result.workerTime_ = workerTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.zhenwei.proto.MineMessage.Worker) {
          return mergeFrom((com.github.zhenwei.proto.MineMessage.Worker)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.zhenwei.proto.MineMessage.Worker other) {
        if (other == com.github.zhenwei.proto.MineMessage.Worker.getDefaultInstance()) return this;
        if (!other.getHandle().isEmpty()) {
          handle_ = other.handle_;
          onChanged();
        }
        if (!other.getWorkerTime().isEmpty()) {
          workerTime_ = other.workerTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.zhenwei.proto.MineMessage.Worker parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.zhenwei.proto.MineMessage.Worker) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object handle_ = "";
      /**
       * <code>string handle = 1;</code>
       * @return The handle.
       */
      public java.lang.String getHandle() {
        java.lang.Object ref = handle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          handle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string handle = 1;</code>
       * @return The bytes for handle.
       */
      public com.google.protobuf.ByteString
          getHandleBytes() {
        java.lang.Object ref = handle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          handle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string handle = 1;</code>
       * @param value The handle to set.
       * @return This builder for chaining.
       */
      public Builder setHandle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        handle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string handle = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHandle() {
        
        handle_ = getDefaultInstance().getHandle();
        onChanged();
        return this;
      }
      /**
       * <code>string handle = 1;</code>
       * @param value The bytes for handle to set.
       * @return This builder for chaining.
       */
      public Builder setHandleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        handle_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object workerTime_ = "";
      /**
       * <code>string workerTime = 2;</code>
       * @return The workerTime.
       */
      public java.lang.String getWorkerTime() {
        java.lang.Object ref = workerTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workerTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string workerTime = 2;</code>
       * @return The bytes for workerTime.
       */
      public com.google.protobuf.ByteString
          getWorkerTimeBytes() {
        java.lang.Object ref = workerTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workerTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string workerTime = 2;</code>
       * @param value The workerTime to set.
       * @return This builder for chaining.
       */
      public Builder setWorkerTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workerTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string workerTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorkerTime() {
        
        workerTime_ = getDefaultInstance().getWorkerTime();
        onChanged();
        return this;
      }
      /**
       * <code>string workerTime = 2;</code>
       * @param value The bytes for workerTime to set.
       * @return This builder for chaining.
       */
      public Builder setWorkerTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workerTime_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Worker)
    }

    // @@protoc_insertion_point(class_scope:Worker)
    private static final com.github.zhenwei.proto.MineMessage.Worker DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.zhenwei.proto.MineMessage.Worker();
    }

    public static com.github.zhenwei.proto.MineMessage.Worker getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Worker>
        PARSER = new com.google.protobuf.AbstractParser<Worker>() {
      @java.lang.Override
      public Worker parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Worker(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Worker> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Worker> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.zhenwei.proto.MineMessage.Worker getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Worker_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Worker_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023MessageEntity.proto\"\247\001\n\tMyMessage\022\035\n\004t" +
      "ype\030\001 \001(\0162\017.MyMessage.Type\022\031\n\006person\030\002 \001" +
      "(\0132\007.PersonH\000\022\031\n\006worker\030\003 \001(\0132\007.WorkerH\000" +
      "\022\017\n\007message\030\004 \001(\t\"(\n\004Type\022\017\n\013PERSON_TYPE" +
      "\020\000\022\017\n\013WORKER_TYPE\020\001B\n\n\010typeBody\"1\n\006Perso" +
      "n\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\003 \001(\005\022\014\n\004addr\030\004 \001" +
      "(\t\",\n\006Worker\022\016\n\006handle\030\001 \001(\t\022\022\n\nworkerTi" +
      "me\030\002 \001(\tB\'\n\030com.github.zhenwei.protoB\013Mi" +
      "neMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyMessage_descriptor,
        new java.lang.String[] { "Type", "Person", "Worker", "Message", "TypeBody", });
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Name", "Age", "Addr", });
    internal_static_Worker_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Worker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Worker_descriptor,
        new java.lang.String[] { "Handle", "WorkerTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
